// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace Sbe
{
    /// <summary>
    /// Boolean Type.
    /// </summary>
    public enum BooleanType : byte
    {
        /// <summary>
        /// False value representation.
        /// </summary>
        F = 0,
        /// <summary>
        /// True value representation.
        /// </summary>
        T = 1,
        NULL_VALUE = 255
    }
}
